### ISSUE TITLE
오류 및 버그 목록들 적어주세요.

### ISSUE THREAD

**Issue by chltmdgh522** [Pironeer-APP/Pironeer_Homework_Web#50]
1. User 과제 페이지 로고 누르면 홈 화면으로 안가짐
2. master/list 페이지에서 로그아웃 누르면 404
3. 로고 추가하기

**Comment by devkev00** [comment]
4. 500 에러 시 관리자 연락메일 수정 바랍니다~ kimminsoo116@gmail.com

**Comment by chltmdgh522** [comment]
네~
