### ISSUE TITLE
초기 파일 설정 모두다 완료했습니다. 확인해주세요.

### ISSUE THREAD

**Issue by chltmdgh522** [Pironeer-APP/Pironeer_Homework_Web#6]
지현이는 그냥 test.html로 했습니다. 워크플로우 잘보고 본인에 방향성에 맞게 바꿔주세요.

최대한 워크플로우랑 비슷하게 해서 아마 이해가 잘 되실거에요.

**Comment by chltmdgh522** [comment]
이젠 서비스가 완성될때까지 main 브랜치의 더 이상의 pr은 없을것입니다.

**Comment by devkev00** [comment]
고생했습니다 ㅎㅎ
